# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statshow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Stat(object):
    def setupUi(self, Stat):
        Stat.setObjectName("Stat")
        Stat.resize(1299, 894)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Stat.sizePolicy().hasHeightForWidth())
        Stat.setSizePolicy(sizePolicy)
        self.gridLayout_3 = QtWidgets.QGridLayout(Stat)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.timeset = QtWidgets.QPushButton(Stat)
        self.timeset.setObjectName("timeset")
        self.gridLayout_2.addWidget(self.timeset, 7, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(Stat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 6, 1)
        self.label_9 = QtWidgets.QLabel(Stat)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 7, 1)
        self.DataText = QtWidgets.QTextBrowser(Stat)
        self.DataText.setObjectName("DataText")
        self.gridLayout_2.addWidget(self.DataText, 3, 3, 5, 2)
        self.label = QtWidgets.QLabel(Stat)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 5)
        self.CodeBox = QtWidgets.QComboBox(Stat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CodeBox.sizePolicy().hasHeightForWidth())
        self.CodeBox.setSizePolicy(sizePolicy)
        self.CodeBox.setMinimumSize(QtCore.QSize(200, 40))
        self.CodeBox.setAcceptDrops(False)
        self.CodeBox.setAutoFillBackground(False)
        self.CodeBox.setObjectName("CodeBox")
        self.gridLayout_2.addWidget(self.CodeBox, 1, 1, 7, 1)
        self.DateSlider = QtWidgets.QSlider(Stat)
        self.DateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.DateSlider.setObjectName("DateSlider")
        self.gridLayout_2.addWidget(self.DateSlider, 1, 3, 2, 2)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.gridLayout_2.setColumnStretch(3, 2)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(Stat)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Stat)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.MaxPriceLabel = QtWidgets.QTextBrowser(Stat)
        self.MaxPriceLabel.setObjectName("MaxPriceLabel")
        self.gridLayout.addWidget(self.MaxPriceLabel, 1, 1, 1, 1)
        self.StdLabel = QtWidgets.QTextBrowser(Stat)
        self.StdLabel.setObjectName("StdLabel")
        self.gridLayout.addWidget(self.StdLabel, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Stat)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Stat)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.MinPriceLabel = QtWidgets.QTextBrowser(Stat)
        self.MinPriceLabel.setObjectName("MinPriceLabel")
        self.gridLayout.addWidget(self.MinPriceLabel, 2, 1, 1, 1)
        self.YearYieldLabel = QtWidgets.QTextBrowser(Stat)
        self.YearYieldLabel.setObjectName("YearYieldLabel")
        self.gridLayout.addWidget(self.YearYieldLabel, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Stat)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Stat)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Stat)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.YieldLabel = QtWidgets.QTextBrowser(Stat)
        self.YieldLabel.setObjectName("YieldLabel")
        self.gridLayout.addWidget(self.YieldLabel, 4, 1, 1, 1)
        self.SharpLabel = QtWidgets.QTextBrowser(Stat)
        self.SharpLabel.setObjectName("SharpLabel")
        self.gridLayout.addWidget(self.SharpLabel, 6, 1, 1, 1)
        self.MeanPriceLabel = QtWidgets.QTextBrowser(Stat)
        self.MeanPriceLabel.setObjectName("MeanPriceLabel")
        self.gridLayout.addWidget(self.MeanPriceLabel, 0, 1, 1, 1)
        self.PlotBox = QtWidgets.QGroupBox(Stat)
        self.PlotBox.setTitle("")
        self.PlotBox.setObjectName("PlotBox")
        self.gridLayout.addWidget(self.PlotBox, 0, 2, 7, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 10)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.gridLayout_3.setRowStretch(0, 2)
        self.gridLayout_3.setRowStretch(1, 2)
        self.gridLayout_3.setRowStretch(2, 8)

        self.retranslateUi(Stat)
        QtCore.QMetaObject.connectSlotsByName(Stat)

    def retranslateUi(self, Stat):
        _translate = QtCore.QCoreApplication.translate
        Stat.setWindowTitle(_translate("Stat", "Form"))
        self.timeset.setText(_translate("Stat", "确定时间"))
        self.label_10.setText(_translate("Stat", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">时间区间调节</span></p></body></html>"))
        self.label_9.setText(_translate("Stat", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">股票代码</span></p></body></html>"))
        self.label.setText(_translate("Stat", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">统计信息</span></p></body></html>"))
        self.label_7.setText(_translate("Stat", "<html><head/><body><p><span style=\" font-size:12pt;\">年化收益</span></p></body></html>"))
        self.label_6.setText(_translate("Stat", "<html><head/><body><p><span style=\" font-size:12pt;\">区间收益</span></p></body></html>"))
        self.label_3.setText(_translate("Stat", "<html><head/><body><p><span style=\" font-size:12pt;\">平均价</span></p></body></html>"))
        self.label_8.setText(_translate("Stat", "<html><head/><body><p><span style=\" font-size:12pt;\">夏普比率</span></p></body></html>"))
        self.label_2.setText(_translate("Stat", "<html><head/><body><p><span style=\" font-size:12pt;\">最高价</span></p></body></html>"))
        self.label_4.setText(_translate("Stat", "<html><head/><body><p><span style=\" font-size:12pt;\">最低价</span></p></body></html>"))
        self.label_5.setText(_translate("Stat", "<html><head/><body><p><span style=\" font-size:12pt;\">区间波动</span></p></body></html>"))


